# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"left_pad": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://{user}.github.io/pyleftpad/"

git_url = "https://github.com/{user}/pyleftpad/tree/master/"

def custom_doc_links(name): return None
