# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['left_pad']

# Cell
def left_pad(padded_string, padding):
    "Pads string with spaces from the left so that its total width equals padding"
    return padded_string.rjust(padding, ' ')